### ISSUE TITLE
"DataSets" Button on UI page doesn't work properly

### ISSUE THREAD

**Issue by wenhuaOpenx** [linkedin/WhereHows#427] opened 2017-04-10 18:03 UTC
After I login and click 'Datasets' button on the home page, neither 'List View' or 'Tree View' shows metadata.
However, if I click 'Flows' and then 'DataSets' button, the tree view of metadata shows up, while the list view is still blank. 
This is the http response I can get if I send a GET request: 

**Request**:
$ curl -H "Content-Type: application/json" -X GET 'http://localhost:9000/api/v1/list/datasets'
**Response**:
{"status":"ok","nodes":[{"datasetId":0,"nodeName":"druid","nodeUrl":"#/datasets/name/druid/page/1?urn=druid:///"},{"datasetId":0,"nodeName":"hive","nodeUrl":"#/datasets/name/hive/page/1?urn=hive:///"}]}

**Comment by Ash-Mishra** [comment] 2018-11-22 11:19
The problem is due to invalid token value. The form is not getting any token so it is not able to make any post request. So instead of toke just substitute ''(empty string) in dataset-comments.js.
Go to dataset-comments.js near line 218 there is create function. In that replace the token assignment to- 
`var token = $("#csrfToken").val()?$("#csrfToken").val().replace('/', ''):'';`

Similarly for remove and update change the token value

**Comment by keremsahin1** [comment] 2019-12-20 23:13
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team

**Closed by keremsahin1** 2019-12-20 23:13 UTC
