### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by dipeshk12886** [linkedin/WhereHows#1355] opened 2018-08-31 16:04 UTC
Hi I am getting while yarm installation step during build execution

> 

> Task :wherehows-web:yarn
yarn install v1.9.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error https://registry.yarnpkg.com/ember-medium-editor/-/ember-medium-editor-0.1.4.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, open 'C:\\Users\\k*\\AppData\\Local\\Yarn\\Cache\\v2\\npm-ember-medium-editor-0.1.4-0955fbde5bd646a44a2874b2b87e594ea034f94c\\Icon\r'"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

> Task :wherehows-web:yarn FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-web:yarn'.
> Process 'command 'C:\Wherehows\WhereHows\wherehows-web\build\yarn\yarn-latest\yarn.cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See 

> https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

***
Have tried removing the Yarn cache couple of times , didnt help.

**Comment by igbopie** [comment] 2018-08-31 23:07
Hi, it is building fine for me. Not sure what happened. Looks like one of the packages was corrupted? Maybe you can try again? try a clean build? sorry I don't have better suggestions for now.

**Comment by sdesa** [comment] 2018-09-04 14:08
I am having the same issue. gradle clean, gradle build --refresh-dependencies did not help. @dipeshk12886 , were you able to solve this?

**Comment by dipeshk12886** [comment] 2018-09-04 14:56
Nope!! No solution yet, tried chaging the yarn version in package as well. Nothing works!!

**Comment by PaulMarginean** [comment] 2018-09-17 12:34
Hello guys,

Any luck on this issue? I also got into it and I'm stuck. The link that "holds" ember editor seems to be working if I access it manually.

I had a look over the ember-medium-editor-0.1.4.tgz file that seems to have an issue, and I noticed that in the yarn.lock file, there is no entry for ember-medium-editor. Can this be the source of the problem?

Any help is more than welcome.

Thanks!

**Comment by theseyi** [comment] 2018-09-28 22:45
Hello @dipeshk12886 @PaulMarginean sorry for the delay. If you could provide detailed steps to reproduce that will help us get to the root of the issue you are experiencing. Thanks.

**Comment by PaulMarginean** [comment] 2018-10-01 12:28
Hello @theseyi,

I cloned the git project and then ran a ./gradlew build command. At some point the execution stops and I get the following message:

> Task :wherehows-web:yarn
yarn install v1.10.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error https://registry.yarnpkg.com/ember-medium-editor/-/ember-medium-editor-0.1.4.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, open 'C:\\Users\\user_name\\AppData\\Local\\Yarn\\Cache\\v2\\npm-ember-medium-editor-0.1.4-0955fbde5bd646a44a2874b2b87e594ea034f94c\\Icon\r'"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Any other info that could help you?

Thanks,
Paul M.

**Comment by dipeshk12886** [comment] 2018-10-01 12:44
Hi @theseyi ,

I am using windows docker and below are the steps I followed:

1. Cloned the repo
2. Copied jdbc jars in wherehows-etl/extralibs 
3. Updated .env file in wherehows-docker dir
4.  executed /wherehows-docker/build.sh 1  

Thanks,
Dipesh

**Comment by wyp0596** [comment] 2018-10-16 12:45
I have the same problem in git bash !
My System is Windows 7.
I try the same command in **Windows CMD,** and it works fine!

**Comment by CristianoMarquesPoa** [comment] 2018-11-27 09:45
Hi, me too have this problem. My docker are instaled on windows 10. I did all the suggested tests but it did not work.

**Comment by cgf120** [comment] 2019-01-15 13:43
you can replace package.json file ember-medium-editor version with  1.0.0-beta.1

**Comment by keremsahin1** [comment] 2019-12-20 23:25
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team

**Closed by keremsahin1** 2019-12-20 23:25 UTC
Labels: build
